# Generated by Django 5.2.5 on 2025-09-05 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'citas',
                'ordering': ('-fecha_hora',),
            },
        ),
        migrations.CreateModel(
            name='CitaSugerida',
            fields=[
                ('id_sugerencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_sugerida', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('origen', models.CharField(default='random_forest', max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('features', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cita_aceptada', models.ForeignKey(blank=True, db_column='id_cita_aceptada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_asociadas', to='api.cita')),
            ],
            options={
                'db_table': 'citas_sugeridas',
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='ControlAcceso',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=30)),
                ('resultado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Control de acceso',
                'verbose_name_plural': 'Control de acceso',
                'db_table': 'control_acceso',
                'ordering': ('-fecha_hora',),
            },
        ),
        migrations.CreateModel(
            name='DiarioEmocional',
            fields=[
                ('id_diario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('titulo_dia', models.CharField(blank=True, max_length=55, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diario_emocional',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='EntrenamientoML',
            fields=[
                ('id_entrenamiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.CharField(max_length=255)),
                ('hiperparametros', models.JSONField(blank=True, null=True)),
                ('metricas', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrenamientos_ml',
                'ordering': ('-fecha_inicio',),
            },
        ),
        migrations.CreateModel(
            name='ModeloML',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('random_forest', 'Random Forest'), ('pln', 'PLN')], max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('fecha_entrenamiento', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('formato', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'modelos_ml',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('trastorno_salud_mental', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('prioridad_clinica', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], default='medio', max_length=10)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='PLNProceso',
            fields=[
                ('id_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_proceso', models.DateTimeField(auto_now_add=True)),
                ('resumen_generado', models.TextField(blank=True, null=True)),
                ('calidad', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('modelo', models.ForeignKey(db_column='id_modelo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pln_procesos', to='api.modeloml')),
            ],
            options={
                'db_table': 'pln_procesos',
            },
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id_psicologo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('numero_matricula', models.CharField(max_length=50, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('numero_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=255, null=True)),
                ('lugar_expedicion_certificado', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
                'db_table': 'psicologos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=55, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('grabacion_audio', models.BinaryField(blank=True, null=True)),
                ('transcripcion', models.TextField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sesiones',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='api.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
        migrations.AddField(
            model_name='entrenamientoml',
            name='modelo',
            field=models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to='api.modeloml'),
        ),
        migrations.AddField(
            model_name='citasugerida',
            name='modelo',
            field=models.ForeignKey(db_column='id_modelo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias', to='api.modeloml'),
        ),
        migrations.AddField(
            model_name='diarioemocional',
            name='paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='api.paciente'),
        ),
        migrations.AddField(
            model_name='citasugerida',
            name='paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='api.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='api.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='psicologo',
            field=models.ForeignKey(db_column='id_psicologo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='api.psicologo'),
        ),
        migrations.AddField(
            model_name='diarioemocional',
            name='psicologo',
            field=models.ForeignKey(db_column='id_psicologo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios', to='api.psicologo'),
        ),
        migrations.AddField(
            model_name='citasugerida',
            name='psicologo',
            field=models.ForeignKey(db_column='id_psicologo', on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='api.psicologo'),
        ),
        migrations.AddField(
            model_name='cita',
            name='psicologo',
            field=models.ForeignKey(db_column='id_psicologo', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='api.psicologo'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='cita',
            field=models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='api.cita'),
        ),
        migrations.AddField(
            model_name='plnproceso',
            name='sesion',
            field=models.ForeignKey(db_column='id_sesion', on_delete=django.db.models.deletion.CASCADE, related_name='pln_procesos', to='api.sesion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='controlacceso',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_acceso', to='api.usuario'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora'], name='citas_fecha_h_d81c1c_idx'),
        ),
    ]
